In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import sys,os
sys.path.append(os.path.expanduser('~/Desktop/ScanCraft/ScanCraft/')) # ubuntu

# 准备数据

In [2]:
import pathlib, pandas

## 读取 csv 文件

In [3]:
def ReadCsvs(path_list,label=0):
    df_dict = {}
    for csv_path in path_list:
        process = csv_path.stem.split('_',1)[1]
        print( f'  {process:7}: {str(csv_path)+',':18}',end='')
        df = pandas.read_csv( csv_path )
        print(f'lines: {df.shape[0]}->dropna->',end='')
        df.dropna( inplace=True )
        print(df.shape[0],end='; ')
        df['process'] = process
        df['label'] = label
        print(f'label={label}')
        df_dict[process] = df
    return df_dict

### 背景

In [4]:
# 查找 csv 文件
BKG_paths = sorted( pathlib.Path().glob('BKG_*.csv') )

In [5]:
BKG_df = ReadCsvs(BKG_paths,0)

  MuMuvv : BKG_MuMuvv.csv,   lines: 523812->dropna->523812; label=0
  TauTau : BKG_TauTau.csv,   lines: 515380->dropna->506988; label=0
  WW     : BKG_WW.csv,       lines: 445118->dropna->430109; label=0
  Wmuv   : BKG_Wmuv.csv,     lines: 1287883->dropna->1268273; label=0
  ZZ     : BKG_ZZ.csv,       lines: 366398->dropna->359179; label=0
  Zh     : BKG_Zh.csv,       lines: 500001->dropna->488489; label=0
  Zll    : BKG_Zll.csv,      lines: 779988->dropna->771374; label=0


### 信号

In [6]:
SGN_paths = [pathlib.Path('./SGN_122_45.csv')]

In [7]:
SGN_df = ReadCsvs(SGN_paths,1)

  122_45 : SGN_122_45.csv,   lines: 4967978->dropna->4967953; label=1


### 整合 DataFrames

In [9]:
df_list = [df for dfd in [SGN_df,BKG_df] for df in dfd.values()]
Data = pandas.concat(df_list, ignore_index=True, copy=False)
print('All data:', Data.shape)

All data: (9316177, 76)


In [10]:
sorted(Data.columns)

['ctheta_mA',
 'ctheta_mB',
 'ctheta_mC',
 'ctheta_mMax',
 'ctheta_mO',
 'ctheta_pA',
 'ctheta_pB',
 'ctheta_pC',
 'ctheta_pMax',
 'ctheta_pO',
 'dRIaIb_A',
 'dRIaIb_B',
 'dRIaIb_C',
 'dRIaIb_O',
 'dRVaIa_A',
 'dRVaIa_B',
 'dRVaIa_C',
 'dRVaIa_O',
 'dRVaVb',
 'dRVbIb_A',
 'dRVbIb_B',
 'dRVbIb_C',
 'dRVbIb_O',
 'label',
 'mInv',
 'mLSPmax',
 'mRCLSP',
 'mRCmax',
 'mRCmin',
 'mRecoil',
 'mVV',
 'pIa_A.E',
 'pIa_A.px',
 'pIa_A.py',
 'pIa_A.pz',
 'pIa_B.E',
 'pIa_B.px',
 'pIa_B.py',
 'pIa_B.pz',
 'pIa_C.E',
 'pIa_C.px',
 'pIa_C.py',
 'pIa_C.pz',
 'pIa_O.E',
 'pIa_O.px',
 'pIa_O.py',
 'pIa_O.pz',
 'pIb_A.E',
 'pIb_A.px',
 'pIb_A.py',
 'pIb_A.pz',
 'pIb_B.E',
 'pIb_B.px',
 'pIb_B.py',
 'pIb_B.pz',
 'pIb_C.E',
 'pIb_C.px',
 'pIb_C.py',
 'pIb_C.pz',
 'pIb_O.E',
 'pIb_O.px',
 'pIb_O.py',
 'pIb_O.pz',
 'pMiss.E',
 'pMiss.px',
 'pMiss.py',
 'pMiss.pz',
 'pVa.E',
 'pVa.px',
 'pVa.py',
 'pVa.pz',
 'pVb.E',
 'pVb.px',
 'pVb.py',
 'pVb.pz',
 'process']

## 保存所有数据至 csv 文件
将 Data 保存至硬盘

In [11]:
Data.to_csv('Data.csv')

## 重新读入参数
**LoadPoint**: 读入所有数据 Data

In [1]:
import pandas

In [2]:
Data = pandas.read_csv('./Data.csv', index_col=0)

In [3]:
Data.iloc[0:5,:]

ctheta_mMax  ctheta_mC  ctheta_mO  ctheta_pO      dRIaIb_O  dRVbIb_C  \
0     0.659805   0.659805   0.711039  -0.711039  3.518750e+00  0.761788   
1     0.054072   0.054072   0.530901  -0.530901  3.143460e+00  0.621042   
2     0.716425   0.716425   0.594378  -0.594378  2.220450e-16  2.258520   
3     0.715991   0.715991   0.905679  -0.905679  0.000000e+00  3.540630   
4     0.722299   0.722299  -0.036763   0.036763  1.110220e-16  2.008010   

   pIa_A.py   pIb_O.pz    pVb.pz  pIb_A.py  ...  dRIaIb_A  dRVaIa_A  dRIaIb_B  \
0  24.78810   3.883110  49.41830 -44.94940  ...   2.59372   1.93458   2.55771   
1  34.65680   0.606065  46.94880  -7.16583  ...   3.99403   1.88743   3.73875   
2 -11.09630  38.210600  -3.67858  49.38030  ...   2.23362   2.73643   2.24983   
3   2.90842 -24.698300  44.12420 -63.26180  ...   2.54963   3.21819   2.57593   
4  52.21440  15.771200 -17.80950 -41.71130  ...   2.76066   2.23936   2.77095   

     dRVaVb  ctheta_pB  ctheta_pA  pIb_C.py  dRVbIb_A  process  label  
0  2.334730  -0.591563  -0.619335  36.30320  0.761788   122_45      1  
1  3.932290  -0.118158  -0.757386  -4.53116  0.621042   122_45      1  
2  2.243170  -0.719274  -0.444524   7.37471  2.258520   122_45      1  
3  0.926963   0.287136  -0.697991 -13.63190  3.540630   122_45      1  
4  2.725980  -0.700130   0.096483  50.86370  2.008010   122_45      1  

[5 rows x 76 columns]

In [4]:
Data.shape

(9316177, 76)

In [5]:
# 检验数据中是否有 nan
Data.dropna().shape

(9316177, 76)

## 取参数

In [6]:
labelwmRC1 = [
        "pVa.px", "pVa.py", "pVa.pz", "pVa.E", 
        "pVb.px", "pVb.py", "pVb.pz", "pVb.E", 
        "mRCmin", "mRCmax", "mRCLSP", "mLSPmax",  # 新变量
        "mRecoil", "mVV", "mInv", "dRVaVb", ] # 新变量

In [7]:
features = Data[labelwmRC1].values
labels = Data["label"].values.reshape(-1,1)

In [8]:
features.shape

(9316177, 16)

In [9]:
labels.shape

(9316177, 1)

## 归一化 features -> U_features
每一列都被归缩放到 (-1, 1)

In [10]:
from sklearn.preprocessing import MaxAbsScaler

In [11]:
scaler = MaxAbsScaler().fit(features)
U_features = scaler.transform(features)

In [12]:
U_features[:3,:]

array([[-0.04970297,  0.29732108, -0.07725772,  0.30471993,  0.39439423,
        -0.12443452,  0.42102918,  0.58319758,  0.37999074,  0.7341262 ,
         0.68413218,  0.41668815,  0.49707524,  0.37425856,  0.4971855 ,
         0.35602825],
       [-0.0776046 ,  0.08018689, -0.37585899,  0.38438374,  0.44469567,
        -0.31209968,  0.39998978,  0.66733238,  0.28989613,  0.66386899,
         0.58300126,  0.32179154,  0.42449601,  0.4935152 ,  0.42459017,
         0.59964378],
       [-0.13620464, -0.42356803, -0.40585601,  0.59012445,  0.40353538,
         0.09638634, -0.0313404 ,  0.41496971,  0.50370414,  0.83771017,
         0.76658222,  0.38311762,  0.40051717,  0.41605573,  0.40060601,
         0.34206606]])

## 区分训练集、测试集

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
        U_features, labels, stratify=labels
    )

In [15]:
for i in [X_train, X_test, y_train, y_test]:
    print(f'{i.shape}, {i.dtype}')

(6987132, 16), float64
(2329045, 16), float64
(6987132, 1), int64
(2329045, 1), int64


In [16]:
# 暂存训练参数
import numpy
numpy.savez('train_data.npz',X_train, X_test, y_train, y_test)

**LoadPoint**: 恢复暂存的数据

In [1]:
# 恢复暂存的数据
import numpy
array = numpy.load('train_data.npz')

In [2]:
X_train, X_test, y_train, y_test = array.values()

In [3]:
for i in [X_train, X_test, y_train, y_test]:
    print(f'{i.shape}, {i.dtype}')

(6987132, 16), float64
(2329045, 16), float64
(6987132, 1), int64
(2329045, 1), int64


# pytorch 训练
检查 torch 和 cuda

In [4]:
import torch
print( 'cuda available: ', torch.cuda.is_available() )
device = torch.accelerator.current_accelerator()
print( f"Using {device} device" )

cuda available:  True
Using cuda device


In [21]:
# 启用同步模式
# import os
# os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

In [22]:
# 释放显存
# torch.cuda.empty_cache()

转移数据到 cuda 或可用设备 device， 注意此时变量名 X_train 等已经*重新指向* **显卡** 上的数据覆盖
* 出现过的问题：读取SGN数据时，没有使用dropna去掉nan数据，导致训练时报错

In [23]:
# device='cpu'

In [5]:
import numpy # 尝试双精度

In [6]:
G_X_train, G_X_test, G_y_train, G_y_test = map(
    lambda a : torch.from_numpy(a.astype(numpy.float32)).to(device),
    [X_train, X_test, y_train, y_test]
)

In [7]:
G_X_train, G_y_test

(tensor([[-0.3478,  0.0549,  0.1832,  ...,  0.2271,  0.5407,  0.1979],
         [ 0.2581,  0.0364,  0.3622,  ...,  0.3237,  0.4944,  0.2996],
         [-0.0515,  0.1437,  0.0243,  ...,  0.3139,  0.1668,  0.4660],
         ...,
         [-0.2878,  0.0748, -0.2132,  ...,  0.3027,  0.4157,  0.2381],
         [-0.0863, -0.1770,  0.3690,  ...,  0.5691,  0.2722,  0.5932],
         [ 0.2256,  0.3165,  0.0150,  ...,  0.1594,  0.5656,  0.1385]],
        device='cuda:0'),
 tensor([[0.],
         [0.],
         [1.],
         ...,
         [0.],
         [0.],
         [1.]], device='cuda:0'))

## 模型

In [8]:
import torch.nn as nn

In [9]:
class SimpleNN(nn.Module):
    def __init__(self, input_size):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, 64)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.sigmoid(self.fc3(x))  # Ensures outputs are in [0, 1]
        return x

In [10]:
# 实例化模型
input_size = X_train.shape[1]
model = SimpleNN(input_size=input_size).to(device)

In [30]:
# next(model.parameters()).device

## 损失函数、优化器

In [11]:
import torch.optim as optim

In [22]:
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

## 训练

In [37]:
epochs = 100
batch_size = 2**25
for epoch in range(epochs):
    model.train()
    total_loss = 0
    num_batches = 0
    permutation = torch.randperm(G_X_train.size()[0])
    for i in range(0, G_X_train.size()[0], batch_size):
        indices = permutation[i:i + batch_size]
        batch_X, batch_y = G_X_train[indices], G_y_train[indices]

        # 前向传播
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)

        # 反向传播和优化
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        num_batches += 1
        # 打印每个批次的损失
#         print(f"Epoch {epoch + 1}/{epochs}, Batch {num_batches}, Loss: {loss.item():.4f}") 
# 由于 batch size 非常大，实际上只循环了一次

    # 计算每个 epoch 的平均损失
    average_loss = total_loss / num_batches
    # 打印每个 epoch 的平均损失
    print(f"Epoch {epoch + 1}/{epochs}, Average Loss: {average_loss:.4f}")

Epoch 1/100, Average Loss: 0.2062
Epoch 2/100, Average Loss: 0.2062
Epoch 3/100, Average Loss: 0.2062
Epoch 4/100, Average Loss: 0.2061
Epoch 5/100, Average Loss: 0.2061
Epoch 6/100, Average Loss: 0.2061
Epoch 7/100, Average Loss: 0.2061
Epoch 8/100, Average Loss: 0.2060
Epoch 9/100, Average Loss: 0.2060
Epoch 10/100, Average Loss: 0.2060
Epoch 11/100, Average Loss: 0.2060
Epoch 12/100, Average Loss: 0.2060
Epoch 13/100, Average Loss: 0.2059
Epoch 14/100, Average Loss: 0.2059
Epoch 15/100, Average Loss: 0.2059
Epoch 16/100, Average Loss: 0.2060
Epoch 17/100, Average Loss: 0.2060
Epoch 18/100, Average Loss: 0.2061
Epoch 19/100, Average Loss: 0.2062
Epoch 20/100, Average Loss: 0.2060
Epoch 21/100, Average Loss: 0.2058
Epoch 22/100, Average Loss: 0.2058
Epoch 23/100, Average Loss: 0.2059
Epoch 24/100, Average Loss: 0.2059
Epoch 25/100, Average Loss: 0.2058
Epoch 26/100, Average Loss: 0.2057
Epoch 27/100, Average Loss: 0.2057
Epoch 28/100, Average Loss: 0.2058
Epoch 29/100, Average Loss: 0

In [15]:
# 显卡信息
import os
exit_status = os.system('nvidia-smi')
print(f"命令退出状态码: {exit_status}")
print(torch.cuda.memory_summary())

Tue Feb 11 18:27:03 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.77.01              Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1080 Ti     On  |   00000000:01:00.0  On |                  N/A |
| 31%   57C    P2             75W /  250W |   10765MiB /  11264MiB |     13%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## 测试

In [25]:
from sklearn.metrics import accuracy_score, roc_auc_score

In [38]:
model.eval()
with torch.no_grad():
    y_pred = model(G_X_test).squeeze().cpu()
    y_pred_labels = (y_pred > 0.5).float()
    accuracy = accuracy_score(y_test, y_pred_labels)
    roc_auc = roc_auc_score(y_test, y_pred)
    print(f"Accuracy: {accuracy:.4f}, ROC-AUC: {roc_auc:.4f}")

Accuracy: 0.9217, ROC-AUC: 0.9668


In [30]:
y_pred_labels

tensor([0., 0., 1.,  ..., 0., 0., 1.])